import Head from 'next/head'
import { makeStaticProps, getStaticPaths } from '../../shared/lib/getStatic'
import { AppLink } from '../../shared/ui/AppLink/AppLink'

export default function Home () {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <AppLink href={'/Congratulations'}>Congratulations</AppLink>
                <AppLink href={'/Verification'}>Verification</AppLink>
            </main>
        </>
    )
}

const getStaticProps = makeStaticProps(['common'])
export { getStaticPaths, getStaticProps }
