import Head from 'next/head'
import { makeStaticProps, getStaticPaths } from '../../shared/lib/getStatic'
import { AppLink } from '../../shared/ui/AppLink/AppLink'
import { Input } from 'shared/ui/Input/Input'
import { FormWrapper } from 'shared/ui/FormWrapper/FormWrapper'

export default function Home () {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <AppLink href={'/Congratulations'}>Congratulations</AppLink>
                <AppLink href={'/Verification'}>Verification</AppLink>
                <AppLink href={'/features/[signIn]'}>Sign In</AppLink>
                <FormWrapper>
                    <Input type={'password'}/>
                </FormWrapper>
            </main>
        </>
    )
}

const getStaticProps = makeStaticProps(['common'])
export { getStaticPaths, getStaticProps }
