import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Button } from 'shared/ui/Button/Button'
import IconArrow from 'shared/assets/icons/general/arrow-back.svg'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Button>Text</Button>
                <IconArrow/>
            </main>
        </>
    )
}
